### ISSUE TITLE
local development environemt

### ISSUE THREAD

**Issue by laterne** [digitalocean-mako/mako#11]
Hi,
Coming from nanobox I am missing the feature to run an entire app locally in a development environment. Will this be supported or is this out of scope for mako?

**Comment by jonfriesen** [comment]
Hey @laterne, running apps locally has not been implemented yet but is on our roadmap. I don't have specifics on when we are going to implementing it but it shouldn't be too far off. Thanks for submitting feedback!

**Comment by jonfriesen** [comment]
(Accidentally closed)

**Comment by laterne** [comment]
Hi @jonfriesen 
Thanks, good to know that it is on the roadmap.
