### ISSUE TITLE
Missing Docker dependency

### ISSUE THREAD

**Issue by iplanwebsites** [digitalocean-mako/mako#12]
![image](https://user-images.githubusercontent.com/787729/68071812-b35ff000-fd54-11e9-8f0d-46589ad65b65.png)
If it's a required local dependency, it should be specified or bundled imho.

**Comment by jonfriesen** [comment]
Hi @iplanwebsites thanks for the feedback. I agree with you and will be opening a ticket internally to alert the user right away that they must have Docker installed.
