### ISSUE TITLE
modify Dockerfile

### ISSUE THREAD

**Issue by laterne** [digitalocean-mako/mako#13]
Hi
is it possible/intended to modify a dockerfile generated by `mako init` or will changes get overwritten? Possible use case: add binaries needed by code, for example imagemagick.

**Comment by jonfriesen** [comment]
Hi @laterne 
You can definitely modify the dockerfile, it shouldn't get overwritten unless you run the `mako init` process again. With NodeJS projects we do copy your project directory into the image, including your binaries in your project directly would eliminate the need to modify the Dockerfile.
