### ISSUE TITLE
databases: Database in Mako vs Managed Databases by Digitalocean

### ISSUE THREAD

**Issue by laterne** [digitalocean-mako/mako#16]
Hi
How will databases, for example postgresql, in mako be positioned against managed databases offered by digital ocean. Are these completely separate products? Do databases in mako offer similar guarantees regarding backup, maintenance or would the owner be responsible for such tasks.

**Comment by jonfriesen** [comment]
Hi @laterne 
The databases that you are exposed to in the Mako CLI are dev databases. They don't come with any maintenance or backup strategy. In the future we will offer integrated support for DigitalOcean's DBaaS which we strongly recommend using for production use.
