### ISSUE TITLE
detecting golang (should be nodejs)

### ISSUE THREAD

**Issue by senechko** [digitalocean-mako/mako#2]
when running `mako push` on a folder that contains a simple hello world file (contents below). i am prompted `Golang app detected, is this correct:`. expected: nodejs detected

```
const http = require('http');

const port = 3000;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello World\n');
});

server.listen(port, () => {
  console.log(`Server running on ${port}`);
});
```

DO $5 droplet running Ubuntu 18.03

**Comment by jonfriesen** [comment]
Thanks for submitting, this is a tough problem to solve in the realm of app detection. Most web apps hold some type of javascript files, many include a index.js despite using different serverside languages.

Currently we detect Node apps if they have a package.json with a start script, or a server.js file in the root which we will run using `node server.js`.

**Comment by mitjafelicijan** [comment]
For me app detection worked. I am no Debian Linux.
