### ISSUE TITLE
Can't install mako on Windows

### ISSUE THREAD

**Issue by jakelevirne** [digitalocean-mako/mako#4]
The install command at mako.digitalocean.com is:
curl -fsSL mako.digitalocean.com/install | bash

But this doesn't work on Windows, even in Powershell.

I'm doing some research to see if [Windows subsystem for Linuyx](https://docs.microsoft.com/en-us/windows/wsl/install-win10) will do the trick.

But on vanilla windows (in my case, Windows 10 Server), installation fails.

**Comment by jonfriesen** [comment]
This is a known issue, we haven't created a installer for Windows yet. You can manually download the mako.exe and use it in a local sense or add it to your system PATH environment variable:
```
curl https://mako.nyc3.digitaloceanspaces.com/cli/windows/mako.exe -o mako.exe
```

**Comment by jonfriesen** [comment]
Small update, we currently have a early installer available for Windows users. [MakoSetup.exe](http://mako.nyc3.digitaloceanspaces.com/cli/windows/MakoSetup.exe).

Some notes:
- It is not signed to identify it's from us (yet) so Windows will make a stink about installing it, but with some coercion it will
- It uses some legacy visuals which we will be subbing out in the near future
