### ISSUE TITLE
json unmarshal error whenever attempting to deploy

### ISSUE THREAD

**Issue by JakeMakesStuff** [digitalocean-mako/mako#6]
When I try and deploy a Mako project (a simple node.js project using the hello world example from [here](https://expressjs.com/en/starter/hello-world.html) or the hello world Flask example from [here](https://pythonspot.com/flask-hello-world/)) after running `mako init` with all the defaults I get the following error:
```
json: cannot unmarshal object into Go struct field SequenceTask.error of type string
```

**Comment by jonfriesen** [comment]
Hi @JakeMakesStuff thanks for submitting an issue! This bug has been fixed, please run `mako update` to get the latest version :slightly_smiling_face:
