### ISSUE TITLE
Building live Docker image (web)  fails for Laravel

### ISSUE THREAD

**Issue by bobbyiliev** [digitalocean-mako/mako#7]
When I try to use the auto Dockerfile generation option for a Laravel 6.x project with PHP 7.2 the build fails with:

`Step 1/13 : FROM php:3-fpm-alpine
manifest for php:3-fpm-alpine not found`

Seems like it is trying to use an image that does not exist.

**Comment by jonfriesen** [comment]
Hey @bobbyiliev thanks for submitting an issue. Currently we only have NodeJS support built into Mako.

**Comment by jonfriesen** [comment]
I'm going to close this issue for now. Stay tuned for more supported languages! :slightly_smiling_face:
