### ISSUE TITLE
Node app not showing under APPS

### ISSUE THREAD

**Issue by cayasso** [digitalocean-mako/mako#9]
I deployed a simple node app but it is not showing under `APPS` dashboard.

```js
const express = require('express')

const app = express()


app.get('/ping', (req, res) => {
  res.json({ ok: true })
})


app.listen(3000, () => {
  console.log('LISTENING TO PORT', 3000)
})

```
package.json

```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.17.1"
  }
}
```

![image](https://user-images.githubusercontent.com/42518/67583339-9dc14980-f708-11e9-90a4-9214f1e85e5f.png)

**Comment by jonfriesen** [comment]
Hi @cayasso thanks for reaching out to us!

I reviewed your account and could not find any apps that are currently deployed. It might be helpful to see the output of your `mako push`. 

Thanks!

**Comment by cayasso** [comment]
Upps sorry! I forgot to paste that info, so this is the URL that I get when pushing but as you see no apps would show up under `APPS`.

Live App : http://dizzy-noodle-97.digioapp.com
Admin    : https://mako.digitalocean.com/go/apps/146a4f21-30a5-4c0f-8669-6f527c177355

![image](https://user-images.githubusercontent.com/42518/67718734-fb1dfa80-f995-11e9-98fd-3edecdf5e855.png)

**Comment by jonfriesen** [comment]
Great, thanks I can confirm that your app is up and running at http://dizzy-noodle-97.digioapp.com/ping

It appears that you are deploying to your personal DigitalOcean account and are signed into a team account in the Mako dashboard. There is a dropdown menu in the top right corner you can use to change teams. 

Can you change to your personal account and let me know if the app shows up?

**Comment by cayasso** [comment]
You are totally right, when I changed to my personal account now I get my apps:

![image](https://user-images.githubusercontent.com/42518/67723586-1e4ea700-f9a2-11e9-857d-7a5e3c45a517.png)

I do saw this message at the bottom:

![image](https://user-images.githubusercontent.com/42518/67723606-2dcdf000-f9a2-11e9-9d82-fce1815f8ef7.png)

**Comment by jonfriesen** [comment]
Awesome! I'm going to pass some feedback to our dashboard engineers to see if we can make the account context a bit more obvious.

Regarding the sequences error, I'm also getting this and will log a bug internally. It should not impact your use of Mako.

Thanks for you feedback, please feel free to log more bugs, questions, or ideas!

**Comment by cayasso** [comment]
Yeah making the account context more obvious would be great, maybe only having one avatar instead of the two, for me it was confusing because I thought the one in front was the current selected and I also didn't even realize that the other was another team account.
Thanks @jonfriesen  I will certainly continue to test and send feedback if necessary.
